rootUrl: http://localhost:8080/components/vaadin-charts/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "78.0"
      platform: "Windows 10"
