sudo: true
dist: trusty
language: node_js
node_js: 8.1

cache:
  directories:
    - node_modules

addons:
  ssh_known_hosts: app.fi

addons:
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY

install:
  - npm install
  - bower install
  - polymer --version
  - npm list polyserve

deploy:
  - provider: script
    script: "./.travis.deploy.sh"
    skip_cleanup: true
    on:
      branch: master

before_script:
  - gulp lint version:check
  - polymer lint --rules polymer-2 --input *.html
  - polymer test --env saucelabs-quick

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      polymer test --env saucelabs-ie && polymer test --env saucelabs-others;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      travis_retry polymer test --env saucelabs-cron;
    fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ccccac989772_key -iv $encrypted_ccccac989772_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
